### ISSUE TITLE
CRC Cards

### ISSUE THREAD

**Issue by WillQizza** [CMPUT301W23T09/QRHunter#26]
For each of the user stories below, they require their CRC related cards. Multiple user stories could potentially use the same cards.
Please ensure that said CRC card fulfills the requirements of the user story before marking it off.

## Player
- [x] #3 (ScannerLocationActivity, ScannerActivity, ScannerController)
- [x] #5 (PlayerProfileActivity, PlayerProfileController, QRCodeListFragment)
- [x] #8 QRCodeListController, PlayerProfileActivity, QRCodeFragment)
- [x] #18 (PlayerProfileActivity, PlayerProfileController, QRCodeListFragment)
- [x] #17 (PlayerProfileActivity, PlayerProfileController)
- [x] #15 (PlayerProfileActivity, PlayerProfileController)
- [x] #6 (PlayerSearchResultsActivity, PlayerSearchFragment, PlayerProfileActivity)

## Game QR Codes
- [x] #20 (ScannerActivity, ScannerLocationActivity, ScannerController)
- [x] #9 (QRCodeListFragment, QRCodeFragment)
- [x] #12 (QRCodeListFragment, QRCodeListController)
- [x] #10 (QRCodeFragment, QRCode)
- [x] #13 (ScannerController, QRCodeListFragment, QRCode)
- [x] #1 (ScannerController, QRCodeListFragment, QRCode)

## Player Profile
- [x] #7 (PlayerEditAccountActivity, PlayerEditAccountController, Player)
- [x] #22 (LandingScreenActivty, LandingScreenController)

## Searching
- [x] #4 (PlayerSearchFragment, PlayerSearchResultsActivity)
- [x] #23 (MapActivity, QRCodeFragment)

## Location
- [x] #2 (QRCodeLocalSearchFragment, MapActivity, MapController)

## Scoring
- [x] #11 (LeaderboardActivity, LeaderboardController, QRCodeDatabase)
- [x] #21 (LeaderboardActivity, LeaderboardController, QRCodeDatabase)

## Privacy
- [x] #14 (ScannerController)
- [x] #16 (ScannerController, ScannerActivity)

# Owner
- [x] #19 (ScannerController)

**Comment by jmmabanta** [comment]
Just a few comments:
- We have two 'Location' crcs (under QRCode and Maps). We should probably get rid of one of them
- I'm not sure if we should have a Leaderboard class for each ranking or one 'Leaderboard' class that stores each ranking (take the data out of LeaderboardController and put it into its own class)
- I feel that the 'Player' object should also contain a collection of QRCodes it scanned. The description 'i should be able to add QR codes to my account' makes it feel natural that way to have players 'have' QR codes.
    - We can still of course have the QRCode keep track of players that scanned it (back reference). This should also help with database query performance if we keep both references
